### ISSUE TITLE
NPE observed when an idle connection is closed and not used

### ISSUE THREAD

**Issue by dilini-muthumala** [wso2/transport-http#370]
**Description:**
The following error being logged in the dashboard carbon logs, in `WSO2 AM Analytics 2.6.0`:

```
[2019-07-02 01:24:53,657] ERROR {org.wso2.msf4j.internal.MSF4JHttpConnectorListener} - Error in http connector listener java.lang.NullPointerException[2019-07-02 01:24:53,657] ERROR {org.wso2.msf4j.internal.MSF4JHttpConnectorListener} - Error in http connector listener java.lang.NullPointerException at org.wso2.transport.http.netty.listener.SourceHandler.handleIdleErrorScenario(SourceHandler.java:286) at org.wso2.transport.http.netty.listener.SourceHandler.userEventTriggered(SourceHandler.java:269) at io.netty.channel.AbstractChannelHandlerContext.invokeUserEventTriggered(AbstractChannelHandlerContext.java:329) at io.netty.channel.AbstractChannelHandlerContext.invokeUserEventTriggered(AbstractChannelHandlerContext.java:315) at io.netty.channel.AbstractChannelHandlerContext.fireUserEventTriggered(AbstractChannelHandlerContext.java:307) at io.netty.handler.timeout.IdleStateHandler.channelIdle(IdleStateHandler.java:371) at io.netty.handler.timeout.IdleStateHandler$ReaderIdleTimeoutTask.run(IdleStateHandler.java:494) at io.netty.handler.timeout.IdleStateHandler$AbstractIdleTask.run(IdleStateHandler.java:466) at io.netty.util.concurrent.PromiseTask$RunnableAdapter.call(PromiseTask.java:38) at io.netty.util.concurrent.ScheduledFutureTask.run(ScheduledFutureTask.java:120) at io.netty.util.concurrent.AbstractEventExecutor.safeExecute(AbstractEventExecutor.java:163) at io.netty.util.concurrent.SingleThreadEventExecutor.runAllTasks(SingleThreadEventExecutor.java:403) at io.netty.channel.nio.NioEventLoop.run(NioEventLoop.java:463) at io.netty.util.concurrent.SingleThreadEventExecutor$5.run(SingleThreadEventExecutor.java:858) at io.netty.util.concurrent.DefaultThreadFactory$DefaultRunnableDecorator.run(DefaultThreadFactory.java:138) at java.lang.Thread.run(Thread.java:745)
```
**Affected Product Version:**
WSO2 AM Analytics 2.6.0
 
**Steps to reproduce:**
This issue could not be recreated on a similar set up; and the cause is unknown.

**Comment by dilini-muthumala** [comment]
What is expected from creating this issue is to fix the code, in order to prevent the NPE.
